<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WatchForge.Testing.FakeNvr</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../libraries/WatchForge.DVRIP.Library/WatchForge.DVRIP.Library.csproj" />
  </ItemGroup>

</Project>
