<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WatchForge.Api</RootNamespace>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../libraries/WatchForge.Interfaces.Library/WatchForge.Interfaces.Library.csproj" />
    <ProjectReference Include="../../../libraries/WatchForge.DVRIP.Library/WatchForge.DVRIP.Library.csproj" />
    <ProjectReference Include="../../../libraries/WatchForge.Processing.Library/WatchForge.Processing.Library.csproj" />
    <ProjectReference Include="../../../libraries/WatchForge.Contracts.Library/WatchForge.Contracts.Library.csproj" />
    <ProjectReference Include="../../../libraries/WatchForge.MotionSentinel.Library/WatchForge.MotionSentinel.Library.csproj" />
  </ItemGroup>

</Project>
