<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <RootNamespace>WatchForge.MotionSentinel.Service.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="coverlet.msbuild" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libraries\WatchForge.MotionSentinel.Library\WatchForge.MotionSentinel.Library.csproj" />
    <ProjectReference Include="..\WatchForge.MotionSentinel.Service\WatchForge.MotionSentinel.Service.csproj" />
  </ItemGroup>

</Project>
